env:
  global: []

install:
  - 'sudo python setup.py install'
  - 'sudo pip install nose'
script:
  - 'nosetests tests'

git:
  depth: 10
language: objective-c
notifications:
  email: false
matrix:
  fast_finish: true
